import type { Centro, Condicionante, Documento, Licenca } from './types';

export const centros: Centro[] = [
  {
    id: 'cd-sp',
    nome: 'CD Cajamar',
    cidade: 'Cajamar',
    estado: 'SP',
    responsavel: 'Marina Azevedo',
    status: 'Operando',
  },
  {
    id: 'cd-jundiai',
    nome: 'CD Jundiaí',
    cidade: 'Jundiaí',
    estado: 'SP',
    responsavel: 'Ricardo Nunes',
    status: 'Operando',
  },
  {
    id: 'cd-extrema',
    nome: 'CD Extrema',
    cidade: 'Extrema',
    estado: 'MG',
    responsavel: 'Bianca Tavares',
    status: 'Operando',
  },
  {
    id: 'cd-joinville',
    nome: 'CD Joinville',
    cidade: 'Joinville',
    estado: 'SC',
    responsavel: 'Caio Martins',
    status: 'Em expansão',
  },
  {
    id: 'cd-goiania',
    nome: 'CD Goiânia',
    cidade: 'Aparecida de Goiânia',
    estado: 'GO',
    responsavel: 'Helena Freitas',
    status: 'Operando',
  },
];

export const initialLicencas: Licenca[] = [
  {
    id: 'lic-1',
    numero: 'CETESB 48001234',
    tipo: 'Licença de Operação',
    centroId: 'cd-sp',
    orgao: 'CETESB',
    emissao: '2023-08-14',
    vencimento: '2025-08-14',
    status: 'A vencer',
    criticidade: 'Alta',
    observacao: 'Renovação deve ser protocolada 120 dias antes do vencimento.',
  },
  {
    id: 'lic-2',
    numero: 'CETESB 57009871',
    tipo: 'Licença de Instalação',
    centroId: 'cd-jundiai',
    orgao: 'CETESB',
    emissao: '2024-02-22',
    vencimento: '2026-02-22',
    status: 'Vigente',
    criticidade: 'Média',
    observacao: 'Obra de ampliação do armazém B.',
  },
  {
    id: 'lic-3',
    numero: 'SEMAD-MG 2024/0198',
    tipo: 'Licença de Operação',
    centroId: 'cd-extrema',
    orgao: 'SEMAD / MG',
    emissao: '2024-06-03',
    vencimento: '2028-06-03',
    status: 'Regular',
    criticidade: 'Baixa',
    observacao: 'Operação condicionada ao relatório anual de efluentes.',
  },
  {
    id: 'lic-4',
    numero: 'IMA-SC 1129/2021',
    tipo: 'Licença Ambiental de Operação',
    centroId: 'cd-joinville',
    orgao: 'IMA / SC',
    emissao: '2021-11-18',
    vencimento: '2025-11-18',
    status: 'A vencer',
    criticidade: 'Alta',
    observacao: 'Iniciar renovação após inspeção do sistema de drenagem.',
  },
  {
    id: 'lic-5',
    numero: 'SEMAD-GO 891/2023',
    tipo: 'Licença Prévia e de Instalação',
    centroId: 'cd-goiania',
    orgao: 'SEMAD / GO',
    emissao: '2023-04-10',
    vencimento: '2025-04-10',
    status: 'Vencida',
    criticidade: 'Alta',
    observacao: 'Aguardando análise de documentação complementar.',
  },
  {
    id: 'lic-6',
    numero: 'CETESB 44006612',
    tipo: 'Outorga de captação',
    centroId: 'cd-sp',
    orgao: 'DAEE / SP',
    emissao: '2024-09-01',
    vencimento: '2029-09-01',
    status: 'Regular',
    criticidade: 'Baixa',
    observacao: 'Captação subterrânea para uso não potável.',
  },
];

export const initialCondicionantes: Condicionante[] = [
  {
    id: 'con-1',
    titulo: 'Enviar relatório trimestral de efluentes',
    licencaId: 'lic-1',
    centroId: 'cd-sp',
    responsavel: 'Marina Azevedo',
    prazo: '2025-03-28',
    status: 'Pendente',
    recorrencia: 'Trimestral',
  },
  {
    id: 'con-2',
    titulo: 'Medição de emissões atmosféricas',
    licencaId: 'lic-1',
    centroId: 'cd-sp',
    responsavel: 'Eduardo Lima',
    prazo: '2025-04-12',
    status: 'Em análise',
    recorrencia: 'Semestral',
  },
  {
    id: 'con-3',
    titulo: 'Atualizar PGRS do empreendimento',
    licencaId: 'lic-3',
    centroId: 'cd-extrema',
    responsavel: 'Bianca Tavares',
    prazo: '2025-05-06',
    status: 'Concluída',
    recorrencia: 'Anual',
  },
  {
    id: 'con-4',
    titulo: 'Apresentar inventário de resíduos',
    licencaId: 'lic-4',
    centroId: 'cd-joinville',
    responsavel: 'Caio Martins',
    prazo: '2025-03-19',
    status: 'Pendente',
    recorrencia: 'Anual',
  },
  {
    id: 'con-5',
    titulo: 'Manutenção do sistema de separação de óleo e água',
    licencaId: 'lic-2',
    centroId: 'cd-jundiai',
    responsavel: 'Ricardo Nunes',
    prazo: '2025-04-01',
    status: 'Pendente',
    recorrencia: 'Mensal',
  },
  {
    id: 'con-6',
    titulo: 'Plano de emergência individual atualizado',
    licencaId: 'lic-5',
    centroId: 'cd-goiania',
    responsavel: 'Helena Freitas',
    prazo: '2025-04-30',
    status: 'Vencida',
    recorrencia: 'Anual',
  },
];

export const initialDocumentos: Documento[] = [
  {
    id: 'doc-1',
    nome: 'Relatório Trimestral de Efluentes — Q4.pdf',
    categoria: 'Relatórios',
    centroId: 'cd-sp',
    atualizadoEm: '18 fev 2025',
    validade: '28 mar 2025',
    status: 'Regular',
    tamanho: '2.4 MB',
    licencaId: 'lic-1',
    condicionanteId: 'con-1',
  },
  {
    id: 'doc-2',
    nome: 'Certificado de Destinação Final — Manifesto MTR.pdf',
    categoria: 'Certificados',
    centroId: 'cd-sp',
    atualizadoEm: '03 mar 2025',
    validade: 'Indeterminada',
    status: 'Vigente',
    tamanho: '840 KB',
    licencaId: 'lic-1',
  },
  {
    id: 'doc-3',
    nome: 'PGRS — Plano de Gerenciamento de Resíduos Sólidos 2024.pdf',
    categoria: 'Planos & Laudos',
    centroId: 'cd-extrema',
    atualizadoEm: '14 jan 2025',
    validade: '06 mai 2025',
    status: 'Concluída',
    tamanho: '6.1 MB',
    licencaId: 'lic-3',
    condicionanteId: 'con-3',
  },
  {
    id: 'doc-4',
    nome: 'Laudo de Análise de Ruído Ambiental.pdf',
    categoria: 'Planos & Laudos',
    centroId: 'cd-jundiai',
    atualizadoEm: '28 nov 2024',
    validade: '28 nov 2025',
    status: 'Regular',
    tamanho: '1.8 MB',
    licencaId: 'lic-2',
  },
  {
    id: 'doc-5',
    nome: 'Licença CETESB 48001234 — Documento Original.pdf',
    categoria: 'Licenças',
    centroId: 'cd-sp',
    atualizadoEm: '14 ago 2023',
    validade: '14 ago 2025',
    status: 'A vencer',
    tamanho: '4.2 MB',
    licencaId: 'lic-1',
  },
  {
    id: 'doc-6',
    nome: 'Comprovante de Protocolo de Renovação SEMAD-GO.pdf',
    categoria: 'Protocolos',
    centroId: 'cd-goiania',
    atualizadoEm: '02 fev 2025',
    validade: '10 abr 2025',
    status: 'Em análise',
    tamanho: '512 KB',
    licencaId: 'lic-5',
    condicionanteId: 'con-6',
  },
];
